# Generated by Django 3.2.6 on 2021-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('dec', models.TextField()),
            ],
        ),
    ]
