# Generated by Django 3.2.6 on 2021-08-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20210825_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='dec',
            new_name='dec1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
